development:
  adapter: postgresql
  encoding: utf8
  database: todo_dev
  host: localhost
  pool: 5
  username: rails_user
  password: 123456

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rails_user
  pool: 5
  username: rails_user
  password: 123456

production:
  adapter: postgresql
  encoding: utf8
  database: todo_prod
  pool: 5
  username: rails_user
  password: 123456
